import { IMetaData } from  './index'
import {  STATUS_DOCUMENT } from './index'

// Generated by https://quicktype.io

export interface IAddItem {
    name:        string;
    description: string;
    quantity:    number;
    brand:       string;
}



// Generated by https://quicktype.io



export interface IItemsReponse extends IMetaData{
    docs: Item[];
}

export type Item = {
    _id:         string;
    name:        string;
    description: string;
    quantity:    number;
    brand:       string;
    status:      STATUS_DOCUMENT;
    createdAt:   string;
    updatedAt:   string;
    __v:         number;
    companyId?:  string;
}


