// Generated by https://quicktype.io

export interface ITreatment {
  companyId: string;
  name: string;
  description: string;
  doctor: string;
  patient: string;
  date: string;
  items: Item[];
}

export interface Item {
  id: string;
  name: string;
  quantity: number;
}
